runtime: nodejs
env: flex
env_variables:
  DB_NAME: "dbbanhang"
  DB_USER: "root"
  DB_PASSWORD: "12345678"
  INSTANCE_CONNECTION_NAME: "db-nmptudw19:asia-southeast1:dbbanhang"
  DB_HOST: "/cloudsql/db-nmptudw19:asia-southeast1:dbbanhang"
beta_settings:
  cloud_sql_instances: "db-nmptudw19:asia-southeast1:dbbanhang"
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
